# Generated by Django 4.2.30 on 2026-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
