# Generated by Django 4.2.30 on 2026-04-19 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('esquema_opciones', models.JSONField(blank=True, default=dict, help_text="Configuración JSON de variantes y recargos. Ej: {'manijas': [{'label': 'Cordón', 'extra': 150}]}")),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
