# Generated by Django 4.2.30 on 2026-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='esquema_opciones',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración JSON de variantes y recargos. Ej: {"manijas": [{"label": "Cordón", "extra": 150}]}'),
        ),
    ]
