# Generated by Django 4.2.30 on 2026-04-19 02:18

from django.db import migrations, models
import django.db.models.deletion
import orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_orden', models.CharField(default=orders.models.generar_codigo_orden, editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En Preparación'), ('LISTO', 'Listo para envío/retiro'), ('DESPACHADO', 'Despachado'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('detalle_carrito', models.JSONField(help_text='Snapshot inmutable de los productos y variantes seleccionadas')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas_cliente', models.TextField(blank=True, help_text='Aclaraciones extra antes de ir a WhatsApp')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='users.cliente')),
            ],
        ),
    ]
