# Generated by Django 4.2.30 on 2026-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_entrega',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono_contacto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
